/**
 * Definizioni campi specifici e checklist allegati per tipologia (codice).
 * Usato da seed iniziale e da migrazione aggiornamento DB.
 */
module.exports.INSURANCE_TYPES_FORM_DEFINITIONS = [
  {
    nome: 'RC Auto / Moto / Autocarri',
    codice: 'rc_auto',
    ordine: 1,
    stato: 'attivo',
    campi: [
      { nome: 'tipologia_preventivo_rc', label: 'Tipo di richiesta', tipo: 'multiselect', opzioni: ['Preventivo per nuova polizza', 'Preventivo per sostituzione veicolo'], obbligatorio: true, ordine: 1 },
      { nome: 'targa', label: 'Targa o Telaio', tipo: 'text', obbligatorio: true, ordine: 2 },
      { nome: 'tipo_veicolo', label: 'Tipo Veicolo', tipo: 'select', opzioni: ['Auto', 'Moto', 'Autocarro', 'Ciclomotore'], obbligatorio: true, ordine: 3 },
      { nome: 'marca', label: 'Marca', tipo: 'text', obbligatorio: true, ordine: 4 },
      { nome: 'modello', label: 'Modello', tipo: 'text', obbligatorio: true, ordine: 5 },
      { nome: 'alimentazione', label: 'Alimentazione', tipo: 'select', opzioni: ['Benzina', 'Diesel', 'GPL', 'Metano', 'Ibrido', 'Elettrico'], obbligatorio: true, ordine: 6 },
      { nome: 'kw', label: 'KW', tipo: 'number', obbligatorio: true, ordine: 7 },
      { nome: 'anno_immatricolazione', label: 'Anno Immatricolazione', tipo: 'number', obbligatorio: true, ordine: 8 },
      { nome: 'valore_veicolo', label: 'Valore Veicolo (€)', tipo: 'number', obbligatorio: false, ordine: 9 },
      { nome: 'proprietario_diverso', label: 'Proprietario diverso dal contraente', tipo: 'boolean', obbligatorio: false, ordine: 10 },
      { nome: 'tipo_guida', label: 'Tipo Guida', tipo: 'select', opzioni: ['Libera', 'Esperta', 'Esclusiva'], obbligatorio: true, ordine: 11 },
      { nome: 'classe_cu', label: 'Classe CU', tipo: 'text', obbligatorio: true, ordine: 12 },
      { nome: 'attestato_rischio', label: 'Attestato di Rischio', tipo: 'text', obbligatorio: false, ordine: 13 },
      { nome: 'garanzie_richieste', label: 'Garanzie Richieste', tipo: 'textarea', obbligatorio: false, ordine: 14 },
      { nome: 'massimale_rc', label: 'Massimale RC', tipo: 'select', opzioni: ['6.450.000€', '10.000.000€', '15.000.000€', '25.000.000€', '50.000.000€'], obbligatorio: true, ordine: 15 },
    ],
    allegati: [
      { nome: 'Libretto Veicolo', obbligatorio: true, ordine: 1 },
      { nome: 'Documento Identità', obbligatorio: true, ordine: 2 },
      { nome: 'Patente', obbligatorio: true, ordine: 3 },
    ],
  },
  {
    nome: 'Casa',
    codice: 'casa',
    ordine: 2,
    stato: 'attivo',
    campi: [
      { nome: 'tipologia_abitazione', label: 'Tipologia Abitazione', tipo: 'select', opzioni: ['Appartamento', 'Villa', 'Villetta a schiera', 'Attico', 'Altro'], obbligatorio: true, ordine: 1 },
      { nome: 'mq', label: 'Metri Quadri', tipo: 'number', obbligatorio: true, ordine: 2 },
      { nome: 'anno_costruzione', label: 'Anno Costruzione', tipo: 'number', obbligatorio: true, ordine: 3 },
      { nome: 'uso', label: 'Uso', tipo: 'select', opzioni: ['Abituale', 'Saltuario'], obbligatorio: true, ordine: 4 },
      { nome: 'proprieta_affitto', label: 'Proprietà o Affitto', tipo: 'select', opzioni: ['Proprietà', 'Affitto'], obbligatorio: true, ordine: 5 },
      { nome: 'indirizzo_immobile', label: 'Indirizzo Immobile', tipo: 'text', obbligatorio: true, ordine: 6 },
      { nome: 'massimale_rct', label: 'Massimale RCT', tipo: 'select', opzioni: ['250.000€', '500.000€', '1.000.000€'], obbligatorio: true, ordine: 7 },
      { nome: '_info_garanzie_casa', label: 'Attenzione - Indicare tutte le garanzie che dovranno essere previste oltre alla RCT, scegliendo tra quelle sotto riportate, anche in caso di sostituzione di polizza esistente.', tipo: 'info', obbligatorio: false, ordine: 8 },
      {
        nome: 'garanzie_casa',
        label: 'Garanzie richieste',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: [
          'Incendio fabbricato',
          'Incendio Contenuto',
          'Ricorso terzi',
          'Socio Politici',
          'Danni da acqua',
          'Ricerca del guasto',
          'Fenomeno elettrico',
          'Atmosferici',
          'Furto Contenuto',
          'RCT Proprietario (facoltativa)',
          'RCT Famiglia (comprende figli minori, animali domestici, vita privata)',
          'Tutela legale',
          'Assistenza',
          'Altre',
        ],
        ordine: 9,
      },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'Affitto Assicurato',
    codice: 'affitto',
    ordine: 3,
    stato: 'attivo',
    campi: [
      { nome: 'canone_mensile', label: 'Canone Mensile (€)', tipo: 'number', obbligatorio: true, ordine: 1 },
      { nome: 'durata_contratto', label: 'Durata Contratto (mesi)', tipo: 'number', obbligatorio: true, ordine: 2 },
      { nome: 'indirizzo_immobile', label: 'Indirizzo Immobile', tipo: 'text', obbligatorio: true, ordine: 3 },
      { nome: 'tipologia_immobile', label: 'Tipologia Immobile', tipo: 'select', opzioni: ['Residenziale', 'Commerciale', 'Ufficio'], obbligatorio: true, ordine: 4 },
      { nome: '_h_affittuario', label: 'Dati Affittuario Immobile', tipo: 'heading', obbligatorio: false, ordine: 5 },
      { nome: 'affittuario_tipologia', label: 'Tipologia affittuario', tipo: 'select', opzioni: ['Persona Fisica', 'Società'], obbligatorio: true, ordine: 6 },
      { nome: 'affittuario_nome', label: 'Nome', tipo: 'text', obbligatorio: true, ordine: 7 },
      { nome: 'affittuario_cognome', label: 'Cognome', tipo: 'text', obbligatorio: true, ordine: 8 },
      { nome: 'affittuario_data_nascita', label: 'Data di nascita', tipo: 'date', obbligatorio: true, ordine: 9 },
      { nome: 'affittuario_comune_nascita', label: 'Comune Nascita', tipo: 'text', obbligatorio: true, ordine: 10 },
      { nome: 'affittuario_provincia_nascita', label: 'Provincia Nascita', tipo: 'text', obbligatorio: true, ordine: 11 },
      { nome: 'affittuario_codice_fiscale', label: 'Codice Fiscale', tipo: 'text', obbligatorio: true, ordine: 12 },
      { nome: 'affittuario_indirizzo_residenza', label: 'Indirizzo di residenza', tipo: 'text', obbligatorio: true, ordine: 13 },
      { nome: 'affittuario_cellulare', label: 'Cellulare', tipo: 'text', obbligatorio: true, ordine: 14 },
      { nome: 'affittuario_email', label: 'Email', tipo: 'text', obbligatorio: true, ordine: 15 },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true, ordine: 1 },
      { nome: 'Codice Fiscale', obbligatorio: true, ordine: 2 },
      { nome: 'Copia Ultima denuncia dei redditi', obbligatorio: true, condizione: 'affittuario_tipologia=Persona Fisica', sezione: 'Se Affittuario Persona Fisica', ordine: 3 },
      { nome: 'Copia Ultima busta paga/Modello Unico/CUD', obbligatorio: true, condizione: 'affittuario_tipologia=Persona Fisica', sezione: 'Se Affittuario Persona Fisica', ordine: 4 },
      { nome: 'Copia documento inquilino', obbligatorio: true, condizione: 'affittuario_tipologia=Persona Fisica', sezione: 'Se Affittuario Persona Fisica', ordine: 5 },
      { nome: 'Proposta di locazione', obbligatorio: true, condizione: 'affittuario_tipologia=Persona Fisica', sezione: 'Se Affittuario Persona Fisica', ordine: 6 },
      { nome: 'Copia certificato camera di commercio', obbligatorio: true, condizione: 'affittuario_tipologia=Società', sezione: 'Se Affittuario Società', ordine: 7 },
      { nome: 'Copia ultimo bilancio', obbligatorio: true, condizione: 'affittuario_tipologia=Società', sezione: 'Se Affittuario Società', ordine: 8 },
      { nome: 'Copia documento rappresentante legale', obbligatorio: true, condizione: 'affittuario_tipologia=Società', sezione: 'Se Affittuario Società', ordine: 9 },
    ],
  },
  {
    nome: 'Sanitaria / Infortuni',
    codice: 'sanitaria',
    ordine: 4,
    stato: 'attivo',
    campi: [
      { nome: '_h_inf', label: 'Garanzie Infortuni', tipo: 'heading', obbligatorio: false, ordine: 1 },
      { nome: '_info_inf', label: 'Attenzione - Indicare tutte le garanzie che dovranno essere previste oltre alla Morte da infortunio e Invalidità Permanente, scegliendo tra quelle sotto riportate, anche in caso di sostituzione di polizza esistente.', tipo: 'info', obbligatorio: false, ordine: 2 },
      {
        nome: 'garanzie_infortuni',
        label: 'Garanzie Infortuni',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: [
          'Morte da infortunio',
          'Invalidità Permanente',
          'Rimborso spese mediche',
          'Inabilità Temporanea',
          'Assistenza',
          'Diaria da ricovero',
          'Altro',
        ],
        ordine: 3,
      },
      { nome: '_h_san', label: 'Garanzie Sanitaria', tipo: 'heading', obbligatorio: false, ordine: 4 },
      { nome: '_info_san', label: 'Attenzione - Indicare tutte le garanzie che dovranno essere previste, scegliendo tra quelle sotto riportate, anche in caso di sostituzione di polizza esistente.', tipo: 'info', obbligatorio: false, ordine: 5 },
      {
        nome: 'garanzie_sanitaria',
        label: 'Garanzie Sanitaria',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: [
          'Rimborso per interventi',
          'Diaria da ricovero SSN',
          'Rimborso spese mediche',
          'Alta diagnostica',
          'Rimborso Ticket SSN',
          'Visite e Accertamenti',
          'Check Up',
          'Fisioterapia',
          'Cure Dentarie',
          'Assistenza',
          'Parto',
          'Altro',
        ],
        ordine: 6,
      },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'Scudo Amico',
    codice: 'scudo_amico',
    ordine: 5,
    stato: 'disattivo',
    campi: [
      { nome: 'attivita_lavorativa', label: 'Attività Lavorativa', tipo: 'text', obbligatorio: true },
      { nome: 'sport_pericolosi', label: 'Sport Pericolosi', tipo: 'boolean', obbligatorio: false },
      { nome: 'patologie_pregresse', label: 'Patologie Pregresse', tipo: 'textarea', obbligatorio: false },
      { nome: 'sinistri_precedenti', label: 'Sinistri Precedenti', tipo: 'textarea', obbligatorio: false },
      { nome: 'polizza_attiva', label: 'Polizza Attiva', tipo: 'boolean', obbligatorio: false },
      { nome: 'beneficiario_caso_morte', label: 'Beneficiario Caso Morte', tipo: 'text', obbligatorio: false },
      { nome: 'garanzie_richieste', label: 'Garanzie Richieste', tipo: 'textarea', obbligatorio: false },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'Miglior Amico Cane/Gatto',
    codice: 'animali',
    ordine: 6,
    stato: 'attivo',
    campi: [
      { nome: 'tipo_animale', label: 'Tipo Animale', tipo: 'select', opzioni: ['Cane', 'Gatto'], obbligatorio: true, ordine: 1 },
      { nome: 'razza', label: 'Razza', tipo: 'text', obbligatorio: true, ordine: 2 },
      { nome: 'data_nascita_animale', label: 'Data Nascita Animale', tipo: 'date', obbligatorio: true, ordine: 3 },
      { nome: 'microchip', label: 'Numero Microchip', tipo: 'text', obbligatorio: true, ordine: 4 },
      {
        nome: 'piano',
        label: 'Piano',
        tipo: 'select',
        opzioni: ['Silver', 'Gold'],
        descrizioni_opzione: {
          Silver:
            'Include coperture con massimali ridotti, ideale per una protezione essenziale a costo contenuto',
          Gold:
            'Include massimali più elevati, in particolare per spese veterinarie, responsabilità civile e tutela legale',
        },
        obbligatorio: true,
        ordine: 5,
      },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'Stranieri',
    codice: 'stranieri',
    ordine: 7,
    stato: 'attivo',
    campi: [
      { nome: 'nazionalita', label: 'Nazionalità', tipo: 'text', obbligatorio: true },
      { nome: 'tipo_richiesta', label: 'Tipo Richiesta', tipo: 'select', opzioni: ['Visto', 'Permesso di soggiorno', 'Ricongiungimento', 'Altro'], obbligatorio: true },
      { nome: 'durata_soggiorno', label: 'Durata Soggiorno (mesi)', tipo: 'number', obbligatorio: true },
      { nome: 'numero_persone', label: 'Numero Persone', tipo: 'number', obbligatorio: true },
      { nome: 'servizi_aggiuntivi', label: 'Servizi Aggiuntivi', tipo: 'textarea', obbligatorio: false },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: false },
      { nome: 'Passaporto', obbligatorio: true },
    ],
  },
  {
    nome: 'RC Professionale',
    codice: 'rc_prof',
    ordine: 8,
    stato: 'attivo',
    campi: [
      { nome: '_h_titolo_studio', label: 'Informazioni sul Titolo di Studio', tipo: 'heading', obbligatorio: false, ordine: 1 },
      { nome: 'tipo_professione', label: 'Tipo professione', tipo: 'text', obbligatorio: true, ordine: 2 },
      { nome: 'laurea', label: 'Laurea', tipo: 'text', obbligatorio: true, ordine: 3 },
      { nome: 'data_iscrizione_albo', label: 'Data iscrizione albo professionale', tipo: 'date', obbligatorio: true, ordine: 4 },
      { nome: 'fatturato', label: 'Fatturato Annuo (€)', tipo: 'number', obbligatorio: true, ordine: 5 },
      { nome: 'attivita_specifiche', label: 'Attività Specifiche', tipo: 'textarea', obbligatorio: false, ordine: 6 },
      { nome: '_h_area_san', label: 'Informazioni Area Sanitaria', tipo: 'heading', obbligatorio: false, ordine: 7 },
      { nome: 'tipo_struttura_operativa', label: 'Tipo di struttura dove opera prevalentemente', tipo: 'text', obbligatorio: true, ordine: 8 },
      { nome: 'inquadramento_professionale', label: 'Inquadramento professionale', tipo: 'text', obbligatorio: true, ordine: 9 },
      { nome: 'interventi_invasivi', label: 'Esegue interventi di tipo invasivo', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 10 },
      { nome: 'medicina_estetica', label: 'Esegue trattamenti di medicina estetica', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 11 },
      { nome: 'chirurgia_vertebrale', label: 'Esegue Interventi di chirurgia vertebrale', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 12 },
      { nome: '_h_gar_acc', label: 'Garanzie Accessorie', tipo: 'heading', obbligatorio: false, ordine: 13 },
      { nome: '_h_gar_tec', label: 'Garanzie accessorie per Area tecnica', tipo: 'heading', obbligatorio: false, ordine: 14 },
      {
        nome: 'garanzie_area_tecnica',
        label: 'Selezione',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: [
          'Attività D. Lgs 81/2008',
          'Attività D. Lgs 624/1996 e s.m.',
          'Sicurezza Informatica e perdita dati',
          'Attività su grandi opere (funivie, gallerie, dighe, ponti)',
        ],
        ordine: 15,
      },
      { nome: '_h_gar_giu', label: 'Garanzie accessorie per area giuridica', tipo: 'heading', obbligatorio: false, ordine: 16 },
      {
        nome: 'garanzie_area_giuridica',
        label: 'Selezione',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: ['Sindaco e Revisore dei Conti', 'Consigliere di amministrazione/Membro OdV', 'Insolvenze/Liquidazioni'],
        ordine: 17,
      },
      { nome: '_h_gar_amm', label: 'Garanzie accessorie per area amministrativa', tipo: 'heading', obbligatorio: false, ordine: 18 },
      {
        nome: 'garanzie_area_amministrativa',
        label: 'Selezione',
        tipo: 'multiselect',
        obbligatorio: false,
        opzioni: [
          'Sindaco e Revisore dei Conti',
          'Consulenza per Fusioni/Acquisizioni',
          'Consigliere di Amministrazione /Membro OdV',
          'Insolvenze/Liquidazioni',
          'Mediazione civile',
          'Visto di conformità leggero e pesante',
          'Responsabile Protezione Dati (DPO)',
        ],
        ordine: 19,
      },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
      { nome: 'Iscrizione Albo', obbligatorio: true },
    ],
  },
  {
    nome: 'Piani di Risparmio',
    codice: 'risparmio',
    ordine: 9,
    stato: 'attivo',
    campi: [
      { nome: '_h_esigenze', label: 'Analisi delle esigenze assicurative', tipo: 'heading', obbligatorio: false, ordine: 1 },
      { nome: 'categoria_lavorativa', label: 'Categoria Lavorativa', tipo: 'select', opzioni: ['Dipendente', 'Autonomo', 'Altro'], obbligatorio: true, ordine: 2 },
      { nome: 'lavoratore_dipendente', label: 'Lavoratore Dipendente', tipo: 'select', opzioni: ['Impiegato', 'Quadro', 'Dirigente', 'Insegnante', 'Dipendente', 'Commesso', 'Operaio', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Dipendente', ordine: 3 },
      { nome: 'lavoratore_autonomo', label: 'Lavoratore Autonomo', tipo: 'select', opzioni: ['Libero professionista', 'Avvocato/Magistrato', 'Commercialista', 'Medico', 'Artigiano', 'Commerciante', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Autonomo', ordine: 4 },
      { nome: 'altre_categorie', label: 'Altre categorie', tipo: 'select', opzioni: ['Casalinga', 'Pensionato', 'Studente', 'Non occupato', 'Titolare di attività', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Altro', ordine: 5 },
      { nome: 'stato_civile', label: 'Stato civile', tipo: 'select', opzioni: ['Celibe/Nubile', 'Coniugato/Convivente', 'Separato/Divorziato', 'Vedovo/a'], obbligatorio: true, ordine: 6 },
      { nome: 'soggetto_a_carico', label: 'Soggetto fiscalmente a carico', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 7 },
      { nome: '_h_contraente', label: 'Analisi delle esigenze assicurative del Contraente/Assicurato', tipo: 'heading', obbligatorio: false, ordine: 8 },
      { nome: 'copertura_altra_polizza', label: 'Nei confronti di quali bisogni è già coperto da altra polizza?', tipo: 'select', opzioni: ['Nessuna copertura assicurativa', 'Protezione (Rischio morte, malattie gravi, non autosufficenza)', 'Risparmio/Investimento', 'Tutela previdenziale'], obbligatorio: true, ordine: 9 },
      { nome: 'obiettivo_principale', label: 'Qual è l’obiettivo principale della copertura che desidera acquistare?', tipo: 'select', opzioni: ['Ricevere una pensione integrativa al termine dell’attività lavorativa', 'Far crescere il capitale investito accettando il rischio di perderne una parte', 'Proteggere il capitale investito', 'Destinare un capitale ai beneficiari designati', 'Altre'], obbligatorio: true, ordine: 10 },
      { nome: 'capitale_investimenti_12_mesi', label: 'Che capitale pensa di destinare agli investimenti assicurativi nei prossimi 12 mesi', tipo: 'select', opzioni: ['Da 0 a 15000,00', 'Da 15000,00 a 50.000,00', 'Oltre 50000,00'], obbligatorio: true, ordine: 11 },
      {
        nome: 'orizzonte_liquidita',
        label: 'Quando investi l’orizzonte temporale è molto importante. Quale delle seguenti affermazioni più le si addice?',
        tipo: 'multiselect',
        obbligatorio: true,
        opzioni: [
          'Potrebbero servirmi anche tra poco ho bisogno di avere la possibilità di prelevare sempre',
          'Ho un fondo per le emergenze posso permettermi di vincolarli anche per 3/5 anni senza particolari problemi',
          'Voglio investire per un periodo di tempo superiore a 5 anni ho abbastanza denaro liquido per sopravvivere ad imprevisti di vario tipo',
        ],
        ordine: 12,
      },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'TCM / Mutuo',
    codice: 'tcm_mutuo',
    ordine: 10,
    stato: 'attivo',
    campi: [
      { nome: '_h_esigenze', label: 'Analisi delle esigenze assicurative', tipo: 'heading', obbligatorio: false, ordine: 1 },
      { nome: 'categoria_lavorativa', label: 'Categoria Lavorativa', tipo: 'select', opzioni: ['Dipendente', 'Autonomo', 'Altro'], obbligatorio: true, ordine: 2 },
      { nome: 'lavoratore_dipendente', label: 'Lavoratore Dipendente', tipo: 'select', opzioni: ['Impiegato', 'Quadro', 'Dirigente', 'Insegnante', 'Dipendente', 'Commesso', 'Operaio', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Dipendente', ordine: 3 },
      { nome: 'lavoratore_autonomo', label: 'Lavoratore Autonomo', tipo: 'select', opzioni: ['Libero professionista', 'Avvocato/Magistrato', 'Commercialista', 'Medico', 'Artigiano', 'Commerciante', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Autonomo', ordine: 4 },
      { nome: 'altre_categorie', label: 'Altre categorie', tipo: 'select', opzioni: ['Casalinga', 'Pensionato', 'Studente', 'Non occupato', 'Titolare di attività', 'Altro'], obbligatorio: true, condizione: 'categoria_lavorativa=Altro', ordine: 5 },
      { nome: 'stato_civile', label: 'Stato civile', tipo: 'select', opzioni: ['Celibe/Nubile', 'Coniugato/Convivente', 'Separato/Divorziato', 'Vedovo/a'], obbligatorio: true, ordine: 6 },
      { nome: 'soggetto_a_carico', label: 'Soggetto fiscalmente a carico', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 7 },
      { nome: '_h_contraente_mutuo', label: 'Analisi delle esigenze assicurative del Contraente/Assicurato', tipo: 'heading', obbligatorio: false, ordine: 8 },
      { nome: 'fumatore', label: 'Fumatore', tipo: 'select', opzioni: ['Sì', 'No (da almeno 2 anni)'], obbligatorio: true, ordine: 9 },
      { nome: 'durata_polizza_anni', label: 'Durata', tipo: 'select', opzioni: ['5 anni', '10 anni', '15 anni', '20 anni', '25 anni', '30 anni', '35 anni', 'Altro'], obbligatorio: true, ordine: 10 },
      { nome: 'capitale_scelto', label: 'Capitale', tipo: 'select', opzioni: ['50000,00', '100000,00', '200000,00', 'Altro'], obbligatorio: true, ordine: 11 },
      { nome: 'mutuo', label: 'Mutuo', tipo: 'select', opzioni: ['Sì', 'No'], obbligatorio: true, ordine: 12 },
      { nome: 'importo_mutuo', label: 'Importo mutuo', tipo: 'text', obbligatorio: false, condizione: 'mutuo=Sì', ordine: 13 },
      { nome: 'durata_mutuo', label: 'Durata mutuo', tipo: 'text', obbligatorio: false, condizione: 'mutuo=Sì', ordine: 14 },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
  {
    nome: 'Check-up Esigenze Varie',
    codice: 'checkup',
    ordine: 11,
    stato: 'attivo',
    campi: [
      { nome: 'attivita_lavorativa', label: 'Attività Lavorativa', tipo: 'text', obbligatorio: true },
      { nome: 'situazione_abitativa', label: 'Situazione Abitativa', tipo: 'select', opzioni: ['Proprietà', 'Affitto', 'Comodato'], obbligatorio: true },
      { nome: 'animali_domestici', label: 'Animali Domestici', tipo: 'boolean', obbligatorio: false },
      { nome: 'viaggi', label: 'Viaggi Frequenti', tipo: 'boolean', obbligatorio: false },
      { nome: 'veicoli_posseduti', label: 'Veicoli Posseduti', tipo: 'textarea', obbligatorio: false },
      { nome: 'coperture_attuali', label: 'Coperture Attuali', tipo: 'textarea', obbligatorio: false },
      { nome: 'persone_da_proteggere', label: 'Persone da Proteggere', tipo: 'number', obbligatorio: false },
    ],
    allegati: [
      { nome: 'Documento Identità', obbligatorio: true },
      { nome: 'Codice Fiscale', obbligatorio: true },
    ],
  },
];
